### PR TITLE
Add additional_scls option for httpd.service.

### PR DESCRIPTION
**Pull request by atopian**
Enable the use of other SCLs for the systemd httpd service.

### CODE REVIEW

**Comment by everestx** [comment]
This seems harmless, however given that the `@additional_scls` variable is going to be set by another external or profile-type module, does it make sense to validate that it exists before setting in the command options?

I'm thinking something like this:

```
<%= @additional_scls || '' %>
```

Maybe I'm making a mountain out of a molehill.

**Comment by skpy** [comment]
I'd rather see the `additional_scls` added as a parameter to the class.  Then the class can evaluate the presence or absence of the parameter appropriately (ie: `validate_array`).  And then the class can join the `ruby_ver` variable with any additional SCLs.  The upshot of this proposal is that there should be no changes to current installs that have no additional SCLs enabled.

**Comment by atopian** [comment]
The problem with adding it as a parameter to the class is that currently httpd.service is not invoked inside of this module, but rather its there so that other (domain specific) modules can invoke it and customize it as needed.

I've updated the PR to handle the conditional case similar to @everestx's suggestion. This way systemd should not get refreshed if `additional_scls` is `undef`

**Comment by skpy** [comment]
The file modified here is actually not used in this module.  It's part of a profile module that makes use of SCL Ruby.  Closing this, and we'll eventually remove this file.

**Pull request closed without merging**
